### ISSUE TITLE
Update DMME's branding to "Virginia Energy"

### ISSUE THREAD

**Issue by athena-small** [coopercenter/va_clean_economy_dashboard#30]
DMME is changing its name to Virginia Energy, effective Oct. 1, 2021. They also have a new logo.

**The task:** Across the dashboard, find all mentions and appearances of the old name and logo, and replace with the new name and logo.

Details below. For the logo, screen grab from this image or (better) search online for a suitable logo image file.

![image](https://user-images.githubusercontent.com/2918094/134205464-3cbae758-d351-4107-a507-8f4403aec0cf.png)

**Comment by arthursmalliii** [comment]
The change-over does not have to take place exactly on Oct. 1. Anytime soon-ish, is fine.

**Comment by arthursmalliii** [comment]
Here's a file with the new Virginia Energy logo.

![VAEnergyLogo](https://user-images.githubusercontent.com/2918094/135475655-19bf7a6b-c869-4b75-b4e7-a26fed81722f.png)

**Comment by arthursmalliii** [comment]
The above logo file is probably fine, but just in case, here's [a link to many alternate versions](https://myuva-my.sharepoint.com/:f:/g/personal/aas9z_virginia_edu/EqH2xC10uNZJmxRi8rH_BRwB8wA8yCwBKaxATIOYCHazdA?e=T95vC2)

**Comment by arthursmalliii** [comment]
On nomenclature:

Virginia Department of Mines Minerals and Energy is now _Virginia Department of Energy_

DMME is now _Virginia Energy_

**Comment by arthursmalliii** [comment]
@EmilyLien Is it just me, or does the white background on the new logo look a little off?

![image](https://user-images.githubusercontent.com/2918094/137628335-699abef9-c94a-4616-b853-db99da812d9f.png)

Suggestions:

- Check if [one of the other file versions](https://myuva-my.sharepoint.com/:f:/g/personal/aas9z_virginia_edu/EqH2xC10uNZJmxRi8rH_BRwB8wA8yCwBKaxATIOYCHazdA?e=T95vC2) looks better. Maybe one with a transparent background instead of a white background.
- Maybe shrink the logo just a bit. Let it float in the title band, instead of pushing up against the top and bottom.
- Add a touch of spacing between the logo and the dashboard title.

**Comment by arthursmalliii** [comment]
Also: The white logo stacked on top of the black menu bar creates a staircase effect that doesn't look right. Especially next to the dark blue title background and the light blue main page.

**Comment by EmilyLien** [comment]
I couldn't find one, so I made one:
![image](https://user-images.githubusercontent.com/67974583/137755828-5281b819-6636-4b63-97fa-4a06f5b296a0.png)

working on the spacing now

**Comment by EmilyLien** [comment]
So I needed to change the DMME in this graph
![image](https://user-images.githubusercontent.com/67974583/137780321-4bd32012-8df6-467e-9ac6-1cd1399ccc3b.png)

however the text within the blocks disappeared, and I did not do anything to change that as far as I can tell (though the information still there in the hovertext). 

![image](https://user-images.githubusercontent.com/67974583/137780659-6841e3d4-aad3-452e-95df-999f23c49191.png)

Should, I try to bring the text within the bars back, or leave it since it was redundant with the hovertext anyway?
